# Generated by Django 4.0.1 on 2022-12-17 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('dissolved_oxygen', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=10)),
                ('ph', models.CharField(max_length=10)),
                ('evaluation', models.CharField(max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='FishPond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='fishPond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='device.fishpond'),
        ),
    ]
