# Generated by Django 4.1.6 on 2023-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpond',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
